
export { default as imgFacebookLogo } from "./facebookLogo.webp" 
export { default as imgInstagramLogo } from "./instagramLogo.webp" 
export { default as imgBarLogo } from "./logoBar.webp"
export { default as imgNavBar } from "./restaurant.jpg"
export { default as LocalAnimado } from "./LocalAnimado.svg"
export { default as FondoLogo } from "./FondoLogo.svg"
export { default as bar1 } from "./1.jpg"
export { default as bar2 } from "./2.svg"
export { default as bar3 } from "./3.svg"
export { default as bar4 } from "./4.svg"
export { default as bar5 } from "./5.jpg"
export { default as bar6 } from "./6.jpg"
export { default as bar7 } from "./7.jpg"
export { default as bar8 } from "./8.jpg"
export { default as bar9 } from "./9.jpg"
export { default as bar10 } from "./10.jpg"
export { default as bar11 } from "./11.jpg"


